### ISSUE TITLE
supporting version 1.12.2

### ISSUE THREAD

**Issue by Mikm159** [ochotonida/trofers#10]
I just found this legendary and interesting mod, but it only supports version 1.16.5 and higher. Do you have the idea of supporting version 1.12.2? I'm sorry for my impoliteness.

**Comment by ochotonida** [comment]
There are no plans for a 1.12 version unfortunately. It's been years since I've modded for 1.12, and I don't really have the time to maintain my mods for Minecraft versions ranging that far back. Backporting this mod specifically would be almost impossible due to all the changes in both Forge and Minecraft since then. (I don't think data packs even existed in 1.12.)
