### ISSUE TITLE
What about modded mobs trophies? And other questions! 

### ISSUE THREAD

**Issue by morceaudebois** [ochotonida/trofers#14]
Hi! Really love the mod, thank you for making it :)

I was wondering if there was a way to add more trophies that would drop for modded mobs? 

I'm also struggling to understand how the different sizes of trophy bases are supposed to work in a survival environment. My gut thinking was that you would be able to craft them and then place the trophies you get from mobs inside, but it doesn't seem to be the case at all since they don't have recipes. Are they just for creative?

And thirdly, I think Trofers would really benefit from having a per-mob drop rate akin to what [Just Mob Heads](https://modrinth.com/mod/just-mob-heads) (and Valheim) do. A drop rate of 0.5 for a rare mob is nice, but if you set it for zombies as well, it can easily get annoying when you have to throw away dozens of them all the time.

Thank you 😊

**Comment by ochotonida** [comment]
Trofers was originally purely a tool for modpack developers, the entity trophies were added later on as an example of what you can do with it. The larger trophy bases aren't obtainable in survival, and are mainly intended to be used by pack devs.

Adding new trophies is possible, although you'll have to create a data pack to do it. The README explains the data format if you're interested. At the moment there's no easy way to make entities drop them if you're using Fabric though.

Trofers already has compatibility for a couple of mods, you're always welcome to suggest more mods here on the issue tracker. I can't promise to add support for every suggested  mod though.

Because I'd like to keep the default data pack at least somewhat maintainable, unfortunately I don't plan on adding a per-mob drop rate for trophies. Adding trophies for new mobs is already quite time-consuming, and I believe most users would prefer the convenience of setting the drop rate for all trophies through a single config option, even if that means some trophies are much rarer than others.

**Comment by morceaudebois** [comment]
Right! Thanks for the comprehensive reply. I'm indeed on Fabric.

It would be nice if there was a database where modpack developers could upload what they do. If somebody has already done the work to make a specific mod compatible with Trofers, then there should be no reason for other modpack developers to do it again. Just an idea though!

The main mods I was thinking about here were [Creeper Overhaul](https://modrinth.com/mod/creeper-overhaul), [The Graveyard](https://modrinth.com/mod/the-graveyard-fabric) and [Naturalist](https://modrinth.com/mod/naturalist).

**Comment by ochotonida** [comment]
The creepers from Creeper Overhaul have animations that can't be turned off last time I looked into it, which unfortunately looks rather weird on a trophy. The Graveyard and Naturalist might have similar issues since they also use GeckoLib, but I haven't properly looked into them yet.
