### ISSUE TITLE
Question regarding resource pack handling (1.18.2 if relevant)

### ISSUE THREAD

**Issue by xFirefalconx** [ochotonida/trofers#17]
Hi, I am using this mod in a modpack on 1.18.2 Forge. 
My modpack utilizes resource packs and replaces entities, too. 
Is there an incompatibility with those, or does it recognize resource packs and replace the entity models accordingly? 

Would love to get some insight. Thanks in advance.

**Comment by ochotonida** [comment]
There shouldn't be any issues with resource packs that just replace entity textures. Since custom entity models (like those from OptiFine) aren't a vanilla feature, I haven't done any testing with them, but I believe that they should still work fine in most cases.
The only exception that I can think of would be stuff that uses GeckoLib, as entities that use GeckoLib usually have issues with their animations when placed on trophies. That's why the default resouce pack currently doesn't have any trophies for mods that use it.

**Comment by xFirefalconx** [comment]
Thanks, I see. I am utilizing EMF which is basically a port of CEM but for Oculus. Some mods I use have GeckoLib, so I will see what happens, in some time. I'll return if I find anything noteworthy to report, albeit it will take a lot of time until I could properly test everything. Let's hope for the best I'd say.
