### ISSUE TITLE
Search Bar & Scrolling

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/trofers#4]
Would it be possible for the creative gui to have a search bar and scrolling added? I created a datapack for pokecube support, but it has over a thousand mobs, making it difficult to find a specific mob. I have to spam click to get to the last page. :D

For example:
[trofers.zip](https://github.com/ochotonida/trofers/files/7230206/trofers.zip)

**Comment by ochotonida** [comment]
Oh my, that's a lot of trophies XD! I'm not very familiar yet with making GUI's, that's why the menu is a bit bare bones right now. A search bar seems doable though. Honestly I'd love to just add the trophies to JEI if I could, but the fact that you can change data packs on the fly makes that rather difficult.

**Comment by WenXin20** [comment]
Ah thanks for looking into it. :)
