### ISSUE TITLE
Loot Tables Question

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/trofers#5]
For example:
[trofers.zip](https://github.com/ochotonida/trofers/files/7230206/trofers.zip)

I have the trofers set to drop the mob loot table, but it doesn't seem to be working. Am I missing something?
```
  "effects": {
    "sound": {
      "soundEvent": "pokecube_mobs:mobs.pikachu"
    },
    "rewards": {
      "lootTable": "pokecube:entities/redstone_rabbit_1",
      "cooldown": 9600
    }
  }
```
And do loot table injects work for modded mobs? Those are also not working.

**Comment by ochotonida** [comment]
I don't see anything wrong with it just from looking at it. Keep in mind that when you place down a trophy, the cooldown starts from the beginning. If that's not it, the only thing I can think of is that the loot table doesn't exist.

Doing loot table injects unfortunately isn't possible with just a data pack. Mods that inject loot also have a bit of code to modify the existing loot table when it's loaded. Usually they'll add a loot pool with a single entry that rolls from the loot pool in the inject folder. Normally you'd be able to use kubeJS to do pretty much the same thing, but it doesn't seem like the entities from PokeCube each have a dedicated loot table. Instead, there's only a few loot tables which are used by multiple entities.

I'm sure there's still a way to modify the drops with kubeJS somehow, but that's not something I'll be able to help much with. I recommend taking a look at their wiki and asking around in their discord if that's something you're interested in.

**Comment by WenXin20** [comment]
Ah I see thanks. The trophy loot table started working now, not sure what changed.
I also am in the Pokecube discord, in fact I help out with it occasionally. :D

**Comment by ochotonida** [comment]
FYI, I've added a global loot modifier to handle trophy drops in the latest update to replace the loot table injections I was using, since injects apparently don't work with non-vanilla loot tables. Unlike the loot table injects, the global loot modifier will work when you use it in your own data pack (even if the entity doesn't have a unique loot table).

Loot modifiers: (you can do it all in one file, I just split it up per mod to keep it organized)
https://github.com/ochotonida/trofers/tree/1.17/src/generated/resources/data/trofers/loot_modifiers
When adding a global loot modifier you need to add it forge's global loot modifier json: (make sure you're using the forge namespace and the same file name)
https://github.com/ochotonida/trofers/tree/1.17/src/generated/resources/data/forge/loot_modifiers

**Comment by WenXin20** [comment]
Ah nice, thanks!

**Comment by WenXin20** [comment]
Is something similar able to be done with chest loot? Because some mobs are not meant to be killed, such as turtles or dolphins, and in the future the Warden.

**Comment by ochotonida** [comment]
No, unfortunately not. I'd have to implement a new global loot modifier that handles chests/containers specifically. When I start working on this mod again I might look into whether implementing such a thing is feasible, but it's not really my top priority right now.

**Comment by WenXin20** [comment]
Ah, I see, thanks.
