### ISSUE TITLE
Massive Googly Eyes

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/trofers#6]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Trofers v2.3.0`
[`Googly Eyes v10.4.0`](https://www.curseforge.com/minecraft/mc-mods/googlyeyes)

If the slime statue ends up with googly eyes, they are absurdly huge. :D 
It also happens to wither, ender dragon, blaze, bee, & phantom torfers if those are added. 
This can be easily reproduced by entering the config for googly eyes and setting the `googly_eye_chance` to 100.

![2021-09-26_01 57 06](https://user-images.githubusercontent.com/12000593/135125690-5a1af325-d3d5-41fe-9232-78548fccc8f3.png)

**Comment by ochotonida** [comment]
I can't seem to reproduce this, would you mind sending your data pack?

**Comment by WenXin20** [comment]
Sure! 
[trofers.zip](https://github.com/ochotonida/trofers/files/7248171/trofers.zip)

**Comment by ochotonida** [comment]
It seems this only affects trophies with animated entities. While I've found the bug that is causing this issue, fixing it in turn causes other rendering problems with animated entities. Honestly, at this point I'm considering disabling the option to animate entities altogether, because it's been causing a lot of issues.
I'll think a bit more about finding a way to fix this, but I probably won't get anywhere.

**Comment by WenXin20** [comment]
Ah, that makes sense! I had enabled animation for flying mobs and slimes for the Better Animation Collection mod, since it looks pretty neat with it. :D
Thanks for looking into this!

**Comment by ochotonida** [comment]
Instead of completely removing the option to make entities animated, I've decided to just remove it from the documentation. You can still use it, but there's not much I can do when you run into issues like these.

**Comment by WenXin20** [comment]
Ah, alright. Thanks for looking into this!
