### ISSUE TITLE
Default textures not used with Quark

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/trofers#7]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Trofers v2.3.0`
[`Quark r2.4-316`](https://www.curseforge.com/minecraft/mc-mods/quark)

When Quark is installed, mobs with variants use quark's shiny texture variants of those mobs. Is there a way to avoid this? Not sure which mod adds the villager iron golem texture though.

![2021-10-02_13 14 35](https://user-images.githubusercontent.com/12000593/135728249-2adc3065-d6f1-478a-b20c-6918ba5ddbcc.png)

**Comment by ochotonida** [comment]
This is semi-intentional, although I should probably make it so entities on trophies don't have these textures by default.
Quark uses the entity UUID to randomly determine the entity texture. Entities on trophies have a UUID of 0 when their nbt doesn't contain one, which always results in a 'shiny' texture. I'm not entirely sure how UUID's are represented in snbt, but using a non-zero UUID should give you a normal variant in most cases.

**Comment by WenXin20** [comment]
Ah, yep, I got the normal skins working by using a datapack and an UUID from a normal variant. And added all the quark variants at the same time. :) I might publish the datapack for it.   


For the pig:
`"nbt": "{UUID: [I; -1883173249, -554614415, -1774000146, 1551098959]}"`

**Comment by ochotonida** [comment]
In the latest update entities will use a non-zero uuid if their nbt doesn't contain one. I've kept the special quark variants of the cow and iron golem since I like those the most :p
